### ISSUE TITLE
TODO list 

### ISSUE THREAD

**Issue by HiroIshida** [HiroIshida/Kinematics.jl#3]
### SHORT TERM
- [ ] reconsider definition of sscc (should the class have mech inside??)
- [ ] add test for pose constraint 

### MID TERM
- [ ] enhance visualization 
- [ ] incorporate aula (**in the previous attempt, the optimization started with in feasible inequality constraints, thus the result was unstable.Now that this bug is fixed by applying the check all the time before the optimization, thus AULA will be successful.**)
### LONG TERM
- [ ] remove dependency on scikit-robot 
- [ ] add planning with caster kinematics

### DONE
- [x] fix position of box sdf (5/1)
- [x] add base motion (5/1)
- [x] add quaternion jacobian (5/1)
- [x] joint limit in planning (5/1)
- [x] compute grad and dist at the same time ?? (5/3)
- [x] compute union sdf (5/5)
- [x] add test for sdfs (5/10)
